//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcWebServiceClientApp.StudentWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        private int TotalMarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalMarks {
            get {
                return this.TotalMarksField;
            }
            set {
                if ((this.TotalMarksField.Equals(value) != true)) {
                    this.TotalMarksField = value;
                    this.RaisePropertyChanged("TotalMarks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentWebService.StudentWebServiceSoap")]
    public interface StudentWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetStudentByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponse GetStudentById(CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        System.Threading.Tasks.Task<CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponse> GetStudentByIdAsync(CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetDateTimeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateTime", ReplyAction="*")]
        CalcWebServiceClientApp.StudentWebService.GetDateTimeResponse GetDateTime(CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<CalcWebServiceClientApp.StudentWebService.GetDateTimeResponse> GetDateTimeAsync(CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentById", Namespace="http://tempuri.org/", Order=0)]
        public CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequestBody Body;
        
        public GetStudentByIdRequest() {
        }
        
        public GetStudentByIdRequest(CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public GetStudentByIdRequestBody() {
        }
        
        public GetStudentByIdRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponseBody Body;
        
        public GetStudentByIdResponse() {
        }
        
        public GetStudentByIdResponse(CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CalcWebServiceClientApp.StudentWebService.Student GetStudentByIdResult;
        
        public GetStudentByIdResponseBody() {
        }
        
        public GetStudentByIdResponseBody(CalcWebServiceClientApp.StudentWebService.Student GetStudentByIdResult) {
            this.GetStudentByIdResult = GetStudentByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateTime", Namespace="http://tempuri.org/", Order=0)]
        public CalcWebServiceClientApp.StudentWebService.GetDateTimeRequestBody Body;
        
        public GetDateTimeRequest() {
        }
        
        public GetDateTimeRequest(CalcWebServiceClientApp.StudentWebService.GetDateTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDateTimeRequestBody {
        
        public GetDateTimeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalcWebServiceClientApp.StudentWebService.GetDateTimeResponseBody Body;
        
        public GetDateTimeResponse() {
        }
        
        public GetDateTimeResponse(CalcWebServiceClientApp.StudentWebService.GetDateTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDateTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDateTimeResult;
        
        public GetDateTimeResponseBody() {
        }
        
        public GetDateTimeResponseBody(string GetDateTimeResult) {
            this.GetDateTimeResult = GetDateTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentWebServiceSoapChannel : CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentWebServiceSoapClient : System.ServiceModel.ClientBase<CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap>, CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap {
        
        public StudentWebServiceSoapClient() {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponse CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap.GetStudentById(CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest request) {
            return base.Channel.GetStudentById(request);
        }
        
        public CalcWebServiceClientApp.StudentWebService.Student GetStudentById(int ID) {
            CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest inValue = new CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest();
            inValue.Body = new CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequestBody();
            inValue.Body.ID = ID;
            CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponse retVal = ((CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap)(this)).GetStudentById(inValue);
            return retVal.Body.GetStudentByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponse> CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap.GetStudentByIdAsync(CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest request) {
            return base.Channel.GetStudentByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalcWebServiceClientApp.StudentWebService.GetStudentByIdResponse> GetStudentByIdAsync(int ID) {
            CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest inValue = new CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequest();
            inValue.Body = new CalcWebServiceClientApp.StudentWebService.GetStudentByIdRequestBody();
            inValue.Body.ID = ID;
            return ((CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap)(this)).GetStudentByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalcWebServiceClientApp.StudentWebService.GetDateTimeResponse CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap.GetDateTime(CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest request) {
            return base.Channel.GetDateTime(request);
        }
        
        public string GetDateTime() {
            CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest inValue = new CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest();
            inValue.Body = new CalcWebServiceClientApp.StudentWebService.GetDateTimeRequestBody();
            CalcWebServiceClientApp.StudentWebService.GetDateTimeResponse retVal = ((CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap)(this)).GetDateTime(inValue);
            return retVal.Body.GetDateTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalcWebServiceClientApp.StudentWebService.GetDateTimeResponse> CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap.GetDateTimeAsync(CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest request) {
            return base.Channel.GetDateTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalcWebServiceClientApp.StudentWebService.GetDateTimeResponse> GetDateTimeAsync() {
            CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest inValue = new CalcWebServiceClientApp.StudentWebService.GetDateTimeRequest();
            inValue.Body = new CalcWebServiceClientApp.StudentWebService.GetDateTimeRequestBody();
            return ((CalcWebServiceClientApp.StudentWebService.StudentWebServiceSoap)(this)).GetDateTimeAsync(inValue);
        }
    }
}
